# Generated by Django 6.0.8 on 2026-08-14 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.core.migration_operations import EnableRowLevelSecurity


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0004_business_seat_hold_minutes'),
        ('clients', '0004_whitelabel_clientinvitation'),
        ('fares', '0002_version_fare_rules'),
        ('network', '0003_route_ordering'),
        ('scheduling', '0002_seed_generation_periodic_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TapCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('channel', models.CharField(choices=[('qr', 'QR code'), ('nfc', 'NFC')], max_length=10)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FareJourney',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('needs_review', 'Needs review')], default='open', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('boarded_at', models.DateTimeField()),
                ('alighted_at', models.DateTimeField(blank=True, null=True)),
                ('alight_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='network.stop')),
                ('board_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='network.stop')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='businesses.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client')),
                ('fare_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fares.farerule')),
                ('fare_segment_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fares.faresegmentrule')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scheduling.trip')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tapngo.tapcredential')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TapEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tap_type', models.CharField(choices=[('board', 'Board'), ('alight', 'Alight')], max_length=10)),
                ('tapped_at', models.DateTimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='businesses.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tapngo.tapcredential')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tapngo.farejourney')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='network.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scheduling.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='farejourney',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('business', 'passenger'), name='one_open_fare_journey_per_business_passenger'),
        ),
        migrations.AddConstraint(
            model_name='farejourney',
            constraint=models.CheckConstraint(condition=models.Q(('fare_rule__isnull', False), ('fare_segment_rule__isnull', False), _negated=True), name='fare_journey_at_most_one_fare_rule'),
        ),
        EnableRowLevelSecurity('TapCredential'),
        EnableRowLevelSecurity('FareJourney'),
        EnableRowLevelSecurity('TapEvent'),
    ]
