# Generated by Django 6.0.8 on 2026-08-17 23:41

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models

from apps.core.migration_operations import EnableRowLevelSecurity


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0004_alter_booking_managers'),
        ('clients', '0005_alter_kycdocument_options_alter_kycdocument_managers_and_more'),
        ('scheduling', '0003_alter_schedule_managers_alter_trip_managers'),
        ('seating', '0006_alter_seat_managers_alter_seatreservation_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kid', models.CharField(max_length=100)),
                ('signed_payload', models.TextField()),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('boarded', 'Boarded'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='issued', max_length=20)),
                ('boarded_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='booking.booking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client')),
                ('seat_reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='seating.seatreservation')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scheduling.trip')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('issued_at'))), name='ticket_expires_after_issued')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        EnableRowLevelSecurity('Ticket'),
    ]
