# Generated by Django 6.0.8 on 2026-08-20 11:31

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.core.migration_operations import EnableRowLevelSecurity


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_alter_kycdocument_options_alter_kycdocument_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notification_type', models.CharField(choices=[('license_expiring', 'Driver license expiring'), ('insurance_expiring', 'Vehicle insurance expiring'), ('roadworthiness_expiring', 'Roadworthiness expiring'), ('ticket_unused_reminder', 'Unused ticket reminder'), ('kyc_document_submitted', 'New KYC document submitted'), ('kyb_document_submitted', 'New KYB document submitted')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('related_object_type', models.CharField(blank=True, max_length=64)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('expiry_snapshot', models.DateField(blank=True, null=True)),
                ('notified_for_date', models.DateField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'notification_type', 'related_object_type', 'related_object_id', 'notified_for_date'), name='unique_notification_per_recipient_type_target_per_day')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        EnableRowLevelSecurity('Notification'),
    ]
