# Generated by Django 6.0.8 on 2026-09-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_seed_sweep_periodic_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('license_expiring', 'Driver license expiring'), ('insurance_expiring', 'Vehicle insurance expiring'), ('roadworthiness_expiring', 'Roadworthiness expiring'), ('ticket_unused_reminder', 'Unused ticket reminder'), ('kyc_document_submitted', 'New KYC document submitted'), ('kyb_document_submitted', 'New KYB document submitted'), ('incident_reported', 'Incident reported'), ('incident_escalated', 'Incident escalated')], max_length=32),
        ),
    ]
