# Generated by Django 6.0.8 on 2026-09-07 20:53

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models

from apps.core.migration_operations import EnableRowLevelSecurity


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0011_drop_tap_and_go_choice'),
        ('clients', '0005_alter_kycdocument_options_alter_kycdocument_managers_and_more'),
        ('fleet', '0003_vehicletype_trip_class'),
        ('scheduling', '0007_trip_actual_arrival_at_trip_actual_departure_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(max_length=100)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='businesses.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleLiveState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('device', 'Device'), ('simulated', 'Simulated')], max_length=16)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed_kph', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('heading_degrees', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='businesses.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduling.trip')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('device', 'Device'), ('simulated', 'Simulated')], max_length=16)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed_kph', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('heading_degrees', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='businesses.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='telemetry.telemetrydevice')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduling.trip')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['vehicle', '-recorded_at'], name='telemetry_v_vehicle_d69a54_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'recorded_at'), name='unique_device_recorded_at')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        EnableRowLevelSecurity('TelemetryDevice'),
        EnableRowLevelSecurity('VehicleLiveState'),
        EnableRowLevelSecurity('VehiclePosition'),
    ]
