# Generated by Django 6.0.8 on 2026-08-10 07:37

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.core.migration_operations import EnableRowLevelSecurity

# docs/adr/0004: the database-level enforcement mechanism for "no two
# active (held/confirmed) SeatReservations for the same seat/trip with
# an overlapping segment_range." btree_gist is required for an
# exclusion constraint mixing equality columns (seat_id, trip_id) with
# a range column (segment_range) — already enabled in the dev Postgres
# image since Phase 0 (docker/postgres/init-extensions.sql), but a
# freshly created test database does NOT inherit that (confirmed
# empirically: `test_integra_afc` had no extensions until this
# migration ran) — so this migration creates it itself rather than
# relying on out-of-band init scripts, the same "own the guarantee,
# don't trust caller/environment setup" principle
# apps.core.rls.platform_staff_bypass already established. `integra_app`
# (the app's non-superuser DB role) can run this: btree_gist has been a
# "trusted" extension since Postgres 13, installable by the owner of a
# database without superuser — verified against this project's own
# docker-compose Postgres image, not assumed.
_ENABLE_BTREE_GIST = "CREATE EXTENSION IF NOT EXISTS btree_gist;"

_EXCLUSION_CONSTRAINT_SQL = """
    ALTER TABLE seating_seatreservation
      ADD CONSTRAINT no_overlapping_active_segment_per_seat_trip
      EXCLUDE USING gist (
        seat_id WITH =,
        trip_id WITH =,
        segment_range WITH &&
      )
      WHERE (status IN ('held', 'confirmed'));
"""
_DROP_EXCLUSION_CONSTRAINT_SQL = (
    "ALTER TABLE seating_seatreservation "
    "DROP CONSTRAINT no_overlapping_active_segment_per_seat_trip;"
)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("booking", "0001_initial"),
        ("clients", "0004_whitelabel_clientinvitation"),
        ("fleet", "0001_initial"),
        ("network", "0003_route_ordering"),
        ("scheduling", "0002_seed_generation_periodic_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("seat_number", models.CharField(max_length=10)),
                ("row", models.PositiveIntegerField(blank=True, null=True)),
                ("column", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clients.client",
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fleet.vehicletype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SeatReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("segment_range", django.contrib.postgres.fields.ranges.IntegerRangeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("held", "Held"),
                            ("confirmed", "Confirmed"),
                            ("expired", "Expired"),
                            ("released", "Released"),
                        ],
                        default="held",
                        max_length=20,
                    ),
                ),
                ("held_until", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="booking.booking",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clients.client",
                    ),
                ),
                (
                    "from_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="network.stop",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="seating.seat",
                    ),
                ),
                (
                    "to_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="network.stop",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="scheduling.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="seat",
            constraint=models.UniqueConstraint(
                fields=("vehicle_type", "seat_number"), name="unique_seat_number_per_vehicle_type"
            ),
        ),
        EnableRowLevelSecurity("Seat"),
        EnableRowLevelSecurity("SeatReservation"),
        migrations.RunSQL(_ENABLE_BTREE_GIST, reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(_EXCLUSION_CONSTRAINT_SQL, reverse_sql=_DROP_EXCLUSION_CONSTRAINT_SQL),
    ]
