# Generated by Django 6.0.8 on 2026-08-16 17:54

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0005_enforce_seatreservation_price_snapshot'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='seat',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='seatreservation',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
