# Generated by Django 6.0.8 on 2026-08-16 11:00

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

from apps.core.migration_operations import EnableRowLevelSecurity


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0004_business_seat_hold_minutes'),
        ('clients', '0004_whitelabel_clientinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entry_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('concession', 'Concession')], max_length=16)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('memo', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='businesses.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('account_type', models.CharField(choices=[('wallet', 'Wallet'), ('business_clearing', 'Business clearing'), ('integra_commission', 'Integra commission'), ('psp_suspense', 'PSP suspense'), ('refund_contra', 'Refund / concession contra')], max_length=32)),
                ('psp_provider', models.CharField(blank=True, max_length=32)),
                ('cached_balance', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('cached_balance_updated_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='businesses.business')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client')),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=8)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.ledgeraccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid_out', 'Paid out'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=8)),
                ('psp_transfer_reference', models.CharField(blank=True, max_length=255)),
                ('psp_transfer_status', models.CharField(blank=True, max_length=64)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='businesses.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='settlement_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.settlementrun'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('account_type', 'wallet')), fields=('business', 'passenger'), name='unique_wallet_account_per_business_passenger'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('account_type', 'business_clearing')), fields=('business',), name='unique_clearing_account_per_business'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('account_type', 'psp_suspense')), fields=('business', 'psp_provider'), name='unique_psp_suspense_account_per_business_provider'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('account_type', 'refund_contra')), fields=('business',), name='unique_refund_contra_account_per_business'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('account_type', 'integra_commission')), fields=('account_type',), name='single_integra_commission_account'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account_type', 'wallet'), ('passenger__isnull', False)), models.Q(models.Q(('account_type', 'wallet'), _negated=True), ('passenger__isnull', True)), _connector='OR'), name='ledger_account_passenger_iff_wallet'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account_type', 'integra_commission'), ('business__isnull', True)), models.Q(models.Q(('account_type', 'integra_commission'), _negated=True), ('business__isnull', False)), _connector='OR'), name='ledger_account_business_iff_not_commission'),
        ),
        migrations.AddConstraint(
            model_name='settlementrun',
            constraint=models.UniqueConstraint(fields=('business', 'period_start', 'period_end'), name='unique_settlement_run_per_business_period'),
        ),
        EnableRowLevelSecurity('LedgerAccount'),
        EnableRowLevelSecurity('SettlementRun'),
        EnableRowLevelSecurity('JournalEntry'),
        EnableRowLevelSecurity('JournalLine'),
    ]
