# Generated by Django 6.0.8 on 2026-08-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_journalentry_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('concession', 'Concession'), ('topup', 'Wallet top-up')], max_length=16),
        ),
    ]
