# Generated by Django 6.0.8 on 2026-09-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_kycdocument_options_alter_kycdocument_managers_and_more'),
        ('ledger', '0004_alter_journalentry_entry_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account', 'created_at'], name='journalline_account_created'),
        ),
    ]
