# Generated by Django 6.0.8 on 2026-08-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stop',
            options={'ordering': ['-created_at']},
        ),
    ]
