# Generated by Django 6.0.8 on 2026-08-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_route_options_alter_stop_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-created_at']},
        ),
    ]
