# Generated by Django 6.0.8 on 2026-08-07 23:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.core.migration_operations import EnableRowLevelSecurity


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_kycdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhiteLabelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('logo', models.URLField(blank=True)),
                ('primary_color', models.CharField(blank=True, max_length=32)),
                ('secondary_color', models.CharField(blank=True, max_length=32)),
                ('email_sender_name', models.CharField(blank=True, max_length=255)),
                ('email_sender_address', models.EmailField(blank=True, max_length=254)),
                ('terms_url', models.URLField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('client',), name='unique_white_label_config_per_client')],
            },
        ),
        EnableRowLevelSecurity('WhiteLabelConfig'),
    ]
