# Generated by Django 6.0.8 on 2026-09-17 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_kycdocument_options_alter_kycdocument_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_marketplace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('is_marketplace', True)), fields=('is_marketplace',), name='single_marketplace_client'),
        ),
    ]
