/**
 * Colour maths for the design system — see
 * docs/specs/14-design-system-and-ui-rebuild.md.
 *
 * Pure functions, no DOM. They exist so two things can be *measured*
 * rather than eyeballed: whether a foreground/background pairing meets
 * WCAG AA, and what an eleven-step ramp derived from one tenant-supplied
 * colour should look like.
 */

export interface Rgb {
  r: number;
  g: number;
  b: number;
}

/**
 * Strictly `#RGB` or `#RRGGBB`, returning `null` for anything else.
 *
 * Deliberately strict: a tenant-supplied string ends up inside a CSS
 * custom property, and this is the only place in the frontend where
 * tenant-controlled data becomes style. Nothing that is not obviously a
 * colour is allowed through — no named colours, no `rgb()`, no
 * `var(--x)`, no trailing junk.
 */
export function parseHex(value: string): Rgb | null {
  const match = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.exec(value.trim());
  if (!match) {
    return null;
  }
  const hex = match[1];
  const full =
    hex.length === 3
      ? hex
          .split('')
          .map((c) => c + c)
          .join('')
      : hex;
  return {
    r: parseInt(full.slice(0, 2), 16),
    g: parseInt(full.slice(2, 4), 16),
    b: parseInt(full.slice(4, 6), 16),
  };
}

export function toHex({ r, g, b }: Rgb): string {
  const channel = (n: number) =>
    Math.max(0, Math.min(255, Math.round(n)))
      .toString(16)
      .padStart(2, '0');
  return `#${channel(r)}${channel(g)}${channel(b)}`;
}

/** sRGB channel (0–255) to linear-light, per WCAG's definition. */
function linearize(channel: number): number {
  const c = channel / 255;
  return c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
}

/** WCAG relative luminance. */
export function relativeLuminance(rgb: Rgb): number {
  return (
    0.2126 * linearize(rgb.r) + 0.7152 * linearize(rgb.g) + 0.0722 * linearize(rgb.b)
  );
}

/** WCAG contrast ratio, 1–21. Order of arguments does not matter. */
export function contrastRatio(a: Rgb, b: Rgb): number {
  const la = relativeLuminance(a);
  const lb = relativeLuminance(b);
  const [light, dark] = la >= lb ? [la, lb] : [lb, la];
  return (light + 0.05) / (dark + 0.05);
}

export const AA_BODY = 4.5;
export const AA_LARGE = 3;
/** WCAG 2.1 AAA body text, the floor Senior Mode's token set is measured against. */
export const AAA_BODY = 7;

const WHITE: Rgb = { r: 255, g: 255, b: 255 };

/**
 * The readable text colour to sit on `background`.
 *
 * White unless white fails AA against it, in which case the darkest step
 * of the background's own ramp. This is what stops a tenant who picks a
 * pale brand colour from shipping white-on-yellow buttons nobody can
 * read — a white-label platform that lets a tenant make their own
 * product illegible has no accessibility story.
 */
export function onColorFor(background: Rgb, dark: Rgb): Rgb {
  return contrastRatio(background, WHITE) >= AA_BODY ? WHITE : dark;
}

// --- OKLab / OKLCH -------------------------------------------------------
// Ramp steps are generated by moving lightness in a perceptual space, not
// in sRGB. Mixing toward white/black in sRGB desaturates unevenly and
// produces muddy mid-steps, which is exactly where a brand colour lives.

interface Oklch {
  l: number;
  c: number;
  h: number;
}

export function rgbToOklch({ r, g, b }: Rgb): Oklch {
  const lr = linearize(r);
  const lg = linearize(g);
  const lb = linearize(b);

  const l = Math.cbrt(0.4122214708 * lr + 0.5363325363 * lg + 0.0514459929 * lb);
  const m = Math.cbrt(0.2119034982 * lr + 0.6806995451 * lg + 0.1073969566 * lb);
  const s = Math.cbrt(0.0883024619 * lr + 0.2817188376 * lg + 0.6299787005 * lb);

  const okL = 0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s;
  const okA = 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s;
  const okB = 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s;

  return {
    l: okL,
    c: Math.sqrt(okA * okA + okB * okB),
    h: Math.atan2(okB, okA),
  };
}

interface LinearRgb {
  lr: number;
  lg: number;
  lb: number;
}

function oklchToLinearRgb({ l: okL, c, h }: Oklch): LinearRgb {
  const okA = c * Math.cos(h);
  const okB = c * Math.sin(h);

  const l = (okL + 0.3963377774 * okA + 0.2158037573 * okB) ** 3;
  const m = (okL - 0.1055613458 * okA - 0.0638541728 * okB) ** 3;
  const s = (okL - 0.0894841775 * okA - 1.291485548 * okB) ** 3;

  return {
    lr: 4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    lg: -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    lb: -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  };
}

const GAMUT_EPSILON = 1e-4;

function inGamut({ lr, lg, lb }: LinearRgb): boolean {
  return [lr, lg, lb].every((c) => c >= -GAMUT_EPSILON && c <= 1 + GAMUT_EPSILON);
}

/**
 * OKLCH to sRGB, **gamut-mapped by reducing chroma** rather than by
 * clamping channels.
 *
 * Much of the OKLCH space has no sRGB equivalent, and the naive approach
 * — compute the channels, then clamp each into 0–255 — silently changes
 * the hue, because the three channels get clipped by different amounts.
 * Measured on the brand ramp before this was fixed: the light steps drifted
 * up to 0.37 radians off the seed hue, so a tenant's "blue" tints came out
 * visibly the wrong colour.
 *
 * Instead, hue and lightness are held fixed and chroma is binary-searched
 * down to the most saturated value that does fit. That is the same
 * strategy CSS Color 4 specifies for gamut mapping, and it fails in the
 * direction a designer expects: slightly less vivid, never a different
 * colour.
 */
export function oklchToRgb(oklch: Oklch): Rgb {
  let { c } = oklch;
  const { l, h } = oklch;

  if (!inGamut(oklchToLinearRgb(oklch))) {
    let low = 0;
    let high = c;
    // 24 iterations resolves chroma far finer than 8-bit output can show.
    for (let i = 0; i < 24; i++) {
      const mid = (low + high) / 2;
      if (inGamut(oklchToLinearRgb({ l, c: mid, h }))) {
        low = mid;
      } else {
        high = mid;
      }
    }
    c = low;
  }

  const { lr, lg, lb } = oklchToLinearRgb({ l, c, h });
  const delinearize = (channel: number) => {
    const clamped = Math.max(0, Math.min(1, channel));
    const v =
      clamped <= 0.0031308 ? clamped * 12.92 : 1.055 * Math.pow(clamped, 1 / 2.4) - 0.055;
    return Math.max(0, Math.min(255, Math.round(v * 255)));
  };

  return { r: delinearize(lr), g: delinearize(lg), b: delinearize(lb) };
}

/** The eleven ramp steps, in order. */
export const RAMP_STEPS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950] as const;
export type RampStep = (typeof RAMP_STEPS)[number];

/**
 * How much of the seed's chroma each step keeps. Tints and shades both
 * lose chroma toward the extremes, which is what keeps a `50` readable as
 * a tint of the brand rather than a pastel of its own.
 */
const CHROMA_SCALE: Record<RampStep, number> = {
  50: 0.12,
  100: 0.24,
  200: 0.42,
  300: 0.62,
  400: 0.85,
  500: 1.0,
  600: 1.0,
  700: 0.94,
  800: 0.84,
  900: 0.74,
  950: 0.62,
};

/** The lightest and darkest ends of any derived ramp. */
const LIGHTEST_L = 0.971;
const DARKEST_L = 0.29;
const ANCHOR: RampStep = 600;

/**
 * An eleven-step ramp derived from the one colour a tenant supplies.
 *
 * **The seed lands exactly on 600**, with its own lightness and chroma,
 * because 600 is the primary action fill — a tenant who enters their
 * brand colour should see that colour on their buttons, not an
 * approximation of it. Lightness then interpolates linearly from a fixed
 * light end (50) up to the seed, and from the seed down to a fixed dark
 * end (950), which keeps the ramp monotonic by construction whatever the
 * seed's own lightness.
 *
 * Hue is held constant throughout; `oklchToRgb` gamut-maps by reducing
 * chroma, so no step can drift to a different colour.
 */
export function deriveRamp(seed: Rgb): Record<RampStep, string> {
  const { l: seedL, c: seedC, h } = rgbToOklch(seed);
  const anchorIndex = RAMP_STEPS.indexOf(ANCHOR);
  const lastIndex = RAMP_STEPS.length - 1;

  const out = {} as Record<RampStep, string>;
  RAMP_STEPS.forEach((step, index) => {
    let l: number;
    if (index === anchorIndex) {
      l = seedL;
    } else if (index < anchorIndex) {
      // 50 → seed, across the light half.
      l = LIGHTEST_L + ((seedL - LIGHTEST_L) * index) / anchorIndex;
    } else {
      // seed → 950, across the dark half.
      l =
        seedL +
        ((DARKEST_L - seedL) * (index - anchorIndex)) / (lastIndex - anchorIndex);
    }
    out[step] = toHex(oklchToRgb({ l, c: seedC * CHROMA_SCALE[step], h }));
  });
  return out;
}
