# Generated by Django 6.0.8 on 2026-08-16 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.core.migration_operations import EnableRowLevelSecurity


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0003_alter_booking_status'),
        ('businesses', '0004_business_seat_hold_minutes'),
        ('clients', '0004_whitelabel_clientinvitation'),
        ('ledger', '0002_seed_integra_commission_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('psp_provider', models.CharField(default='paystack', max_length=32)),
                ('psp_reference', models.CharField(max_length=255, unique=True)),
                ('psp_authorization_url', models.CharField(blank=True, max_length=500)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('requires_manual_refund', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='booking.booking')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='businesses.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaystackAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_code', models.CharField(blank=True, max_length=255)),
                ('bank_code', models.CharField(blank=True, max_length=16)),
                ('account_number', models.CharField(blank=True, max_length=32)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='businesses.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('psp_provider', models.CharField(max_length=32)),
                ('event_type', models.CharField(max_length=64)),
                ('reference', models.CharField(max_length=255)),
                ('signature_valid', models.BooleanField()),
                ('raw_payload', models.JSONField()),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.paymentintent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('booking',), name='one_pending_payment_intent_per_booking'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('psp_provider', 'reference', 'event_type'), name='unique_webhook_event_per_provider_reference_type'),
        ),
        # WebhookEvent is deliberately NOT RLS-enabled here — it isn't a
        # BaseModel subclass (see its own docstring): it must be
        # writable before any tenancy context exists, since Paystack
        # calls a public, unauthenticated endpoint.
        EnableRowLevelSecurity('PaymentIntent'),
        EnableRowLevelSecurity('PaystackAccount'),
    ]
