# Generated by Django 6.0.8 on 2026-08-19 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_managers'),
        ('businesses', '0005_alter_business_options_alter_kybdocument_options_and_more'),
        ('clients', '0005_alter_kycdocument_options_alter_kycdocument_managers_and_more'),
        ('ledger', '0004_alter_journalentry_entry_type'),
        ('payments', '0002_alter_paymentintent_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='intent_type',
            field=models.CharField(choices=[('booking_payment', 'Booking payment'), ('wallet_topup', 'Wallet top-up')], default='booking_payment', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='wallet_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='businesses.business'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='booking.booking'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', False), ('intent_type', 'booking_payment'), ('wallet_business__isnull', True)), models.Q(('booking__isnull', True), ('intent_type', 'wallet_topup'), ('wallet_business__isnull', False)), _connector='OR'), name='payment_intent_booking_xor_wallet_business'),
        ),
    ]
