# Generated by Django 6.0.8 on 2026-08-23 16:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentintent_intent_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='wallet_component_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
