# Generated by Django 6.0.8 on 2026-09-03 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_booking_business_created_and_more'),
        ('businesses', '0011_drop_tap_and_go_choice'),
        ('clients', '0005_alter_kycdocument_options_alter_kycdocument_managers_and_more'),
        ('ledger', '0005_journalline_journalline_account_created'),
        ('payments', '0004_paymentintent_wallet_component_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='channel',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['business', 'created_at'], name='paymentintent_biz_created'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['business', 'status'], name='paymentintent_biz_status'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['business', 'channel'], name='paymentintent_biz_channel'),
        ),
    ]
