# Generated by Django 6.0.8 on 2026-09-03 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_open_seating_fields'),
        ('businesses', '0011_drop_tap_and_go_choice'),
        ('clients', '0005_alter_kycdocument_options_alter_kycdocument_managers_and_more'),
        ('network', '0005_route_available_trip_classes'),
        ('scheduling', '0006_schedule_trip_class_trip_trip_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['business', 'created_at'], name='booking_business_created'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['business', 'status'], name='booking_business_status'),
        ),
    ]
