import AxeBuilder from '@axe-core/playwright';
import { expect, test, type Page } from '@playwright/test';

const EMAIL = 'e2e-client-staff@example.com';
const PASSWORD = 'e2e-test-password-123';
const NETWORK_BUSINESS = 'Integra E2E Network Test Business';
const PER_SEGMENT_BUSINESS = 'Integra E2E Per-Segment Fare Business';
const PER_SEGMENT_ROUTE = 'Apapa → Ojota';

function uniqueSuffix(): string {
  return `${Date.now()}-${Math.floor(Math.random() * 10000)}`;
}

async function signIn(page: Page): Promise<void> {
  await page.goto('/login');
  await page.getByLabel('Email').fill(EMAIL);
  await page.getByLabel('Password').fill(PASSWORD);
  await page.getByRole('button', { name: 'Sign in' }).click();
  await expect(page).toHaveURL(/\/home$/);
}

async function selectActiveBusiness(page: Page, name: string): Promise<void> {
  await page.getByRole('button', { name: new RegExp(EMAIL) }).click();
  await page.getByRole('menuitemradio', { name }).click();
}

/**
 * Switches grids and waits until the table really holds that class.
 *
 * The legend and heading change the moment the selector does, while the
 * amounts arrive a request later — so asserting on the legend alone
 * races the data. The grid marks itself `aria-busy` and disables its
 * cells for exactly that window, which is what this waits out.
 */
async function selectClass(page: Page, label: string): Promise<void> {
  await page.getByLabel('Service class').selectOption({ label });
  await expect(page.locator('[aria-busy="true"]')).toHaveCount(0);
}

/**
 * Service classes end to end — docs/specs/15-trip-classes.md.
 *
 * The spec's own §E2E asks to confirm that "a generated Trip carries
 * the class". **That step is a manual trip here instead**, stated
 * rather than skipped: trips are generated by a nightly Celery Beat
 * job, which a Playwright run cannot trigger. The Schedule→Trip
 * snapshot itself is covered by
 * `apps/scheduling/tests/test_trip_classes.py`, which asserts both that
 * a generated trip takes its schedule's class and that editing the
 * schedule afterwards does not retro-change it. What is left here is
 * everything only a browser can prove.
 */
test.describe('client-admin-app trip classes', () => {
  test('runs a premium service end to end, and refuses a mini vehicle on it', async ({ page }) => {
    const suffix = uniqueSuffix();
    const routeName = `E2E Premium Route ${suffix}`;
    const premiumType = `E2E Premium Type ${suffix}`;
    const miniType = `E2E Mini Type ${suffix}`;
    const miniRegistration = `E2E-${suffix.slice(-4)}-MN`;

    await signIn(page);
    await selectActiveBusiness(page, NETWORK_BUSINESS);

    // --- A route that offers Premium, and only Premium -------------
    await page.goto('/routes/new');
    await page.getByLabel('Route name').fill(routeName);
    // Before any class is ticked the group must say what empty means,
    // or an all-unchecked group reads as "no classes allowed" — the
    // opposite of the truth, and the state every pre-spec-15 route is
    // in.
    await expect(page.getByText('accepts every class')).toBeVisible();
    await page.getByRole('checkbox', { name: 'Premium' }).check();
    await expect(page.getByText('accepts every class')).toHaveCount(0);
    await page.getByRole('button', { name: 'Create route' }).click();
    await expect(page).toHaveURL(/\/routes\/[^/]+\/edit$/);
    // Round-trips: the allow-list came back from the server checked.
    await expect(page.getByRole('checkbox', { name: 'Premium' })).toBeChecked();
    await expect(page.getByRole('checkbox', { name: 'Mini' })).not.toBeChecked();

    // --- Two vehicle types, one of each class ----------------------
    await page.goto('/vehicle-types/new');
    await page.getByLabel('Name').fill(premiumType);
    await page.getByLabel('Capacity (seats)').fill('20');
    await page.getByLabel('Service class').selectOption({ label: 'Premium' });
    await page.getByRole('button', { name: 'Create vehicle type' }).click();
    await expect(page).toHaveURL(/\/vehicle-types$/);

    await page.goto('/vehicle-types/new');
    await page.getByLabel('Name').fill(miniType);
    await page.getByLabel('Capacity (seats)').fill('14');
    await page.getByLabel('Service class').selectOption({ label: 'Mini' });
    await page.getByRole('button', { name: 'Create vehicle type' }).click();
    await expect(page).toHaveURL(/\/vehicle-types$/);

    await page.goto('/vehicles/new');
    await page.getByLabel('Vehicle type').selectOption({ label: `${miniType} (14 seats)` });
    await page.getByLabel('Registration number').fill(miniRegistration);
    await page.getByRole('button', { name: 'Create vehicle' }).click();
    await expect(page).toHaveURL(/\/vehicles$/);

    // --- A Premium schedule on the Premium-only route --------------
    await page.goto('/schedules/new');
    await page.getByLabel('Route').selectOption({ label: routeName });
    // The route offers Premium alone, so that is the only option the
    // picker may show: an option the backend would refuse with a 400
    // must never be offered in the first place.
    const classSelect = page.getByLabel('Service class');
    await expect(classSelect.locator('option')).toHaveText(['Premium']);
    await page.getByRole('checkbox', { name: 'Mon' }).check();
    await page.getByLabel('Departure time').fill('07:30');
    await page.getByLabel('Effective from').fill('2026-01-01');
    await page.getByRole('button', { name: 'Create schedule' }).click();
    await expect(page).toHaveURL(/\/schedules$/);

    // --- A Premium trip on it --------------------------------------
    await page.goto('/trips/new');
    await page.getByLabel('Route').selectOption({ label: routeName });
    await expect(page.getByLabel('Service class').locator('option')).toHaveText(['Premium']);
    await page.getByLabel('Service date').fill('2026-12-15');
    await page.getByLabel('Departure time').fill('08:00');
    await page.getByRole('button', { name: 'Create trip' }).click();
    await expect(page).toHaveURL(/\/trips$/);

    await page.getByLabel('Search trips').fill(routeName);
    const row = page.getByRole('row', { name: new RegExp(routeName) }).first();
    await expect(row).toBeVisible();
    await expect(row).toContainText('Premium');

    const results = await new AxeBuilder({ page })
      .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'])
      .analyze();
    expect(results.violations).toEqual([]);

    // --- Assigning a Mini vehicle to it is refused -----------------
    // Selling Premium and running a Mini is a refund event, and this
    // system has no refund service, so it is blocked at assignment
    // rather than recorded and left for someone to notice.
    await row.getByRole('button', { name: new RegExp('^Actions for') }).click();
    await page.getByRole('menuitem', { name: 'Assign vehicle & driver' }).click();
    const drawer = page.getByRole('dialog');
    await expect(drawer).toBeVisible();
    await drawer.getByLabel('Vehicle').selectOption({ label: miniRegistration });
    await drawer.getByRole('button', { name: 'Save assignment' }).click();

    await expect(page.getByText(/is a mini vehicle/)).toBeVisible();
    await expect(page.getByText(/premium service/)).toBeVisible();
  });

  test('prices a class-specific grid without disturbing the Any class one', async ({ page }) => {
    await signIn(page);
    await selectActiveBusiness(page, PER_SEGMENT_BUSINESS);
    await page.getByRole('link', { name: 'Routes' }).click();

    const routeRow = page.getByRole('row', { name: new RegExp(PER_SEGMENT_ROUTE) }).first();
    await routeRow.getByRole('button', { name: new RegExp('^Actions for') }).click();
    await page.getByRole('menuitem', { name: 'Fares' }).click();
    await expect(page).toHaveURL(/\/fares\/fare-matrix\//);

    // The grid opens on the wildcard, where every price set before
    // classes existed lives.
    await expect(page.getByLabel('Service class')).toHaveValue('');
    const wildcardAmount = await page.getByLabel('Apapa to Surulere fare').inputValue();
    expect(wildcardAmount).not.toBe('');

    await selectClass(page, 'Premium');
    await expect(page.getByText('A greyed amount is not set for this class')).toBeVisible();

    const premiumCell = page.getByLabel('Apapa to Surulere fare');

    // This dev/CI database keeps everything a previous run wrote, so
    // the Premium cell may already be priced from last time. Clear it
    // back to inherited first — which also exercises the closing path —
    // rather than asserting a state only a first-ever run would have.
    if ((await premiumCell.inputValue()) !== '') {
      await premiumCell.fill('');
      await page.getByRole('button', { name: 'Save fares' }).click();
      await page.getByRole('button', { name: 'Stop selling these segments' }).click();
      await expect(page.getByText(/Saved 1 fare\./)).toBeVisible();
    }

    // The heart of it: Premium prices nothing of its own, so the cell is
    // empty *and* shows what a passenger would actually be charged.
    // Rendering it as simply blank would say the opposite.
    await expect(premiumCell).toHaveValue('');
    await expect(premiumCell).toHaveAttribute('placeholder', wildcardAmount);
    // Nothing is dirty, so nothing can be saved by accident — an
    // inherited amount must never be mistaken for an edit.
    await expect(page.getByText('No unsaved changes')).toBeVisible();
    await expect(page.getByRole('button', { name: 'Save fares' })).toBeDisabled();

    const premiumAmount = String(Number(wildcardAmount.split('.')[0]) * 3 + 7);
    await premiumCell.fill(premiumAmount);
    await page.getByRole('button', { name: 'Save fares' }).click();
    await expect(page.getByText(/Saved 1 fare\./)).toBeVisible();
    await expect(premiumCell).toHaveValue(`${premiumAmount}.00`);
    // Now owned rather than inherited, so the placeholder is gone.
    await expect(premiumCell).not.toHaveAttribute('placeholder', /./);

    // And the Any class grid it used to inherit from is untouched —
    // the isolation this whole parameter exists to guarantee.
    await selectClass(page, 'Any class');
    await expect(page.getByLabel('Apapa to Surulere fare')).toHaveValue(wildcardAmount);
  });

  test('warns before a class switch throws away unsaved edits', async ({ page }) => {
    await signIn(page);
    await selectActiveBusiness(page, PER_SEGMENT_BUSINESS);
    await page.getByRole('link', { name: 'Routes' }).click();
    const routeRow = page.getByRole('row', { name: new RegExp(PER_SEGMENT_ROUTE) }).first();
    await routeRow.getByRole('button', { name: new RegExp('^Actions for') }).click();
    await page.getByRole('menuitem', { name: 'Fares' }).click();

    const original = await page.getByLabel('Apapa to Surulere fare').inputValue();
    await page.getByLabel('Apapa to Surulere fare').fill('4321');
    await expect(page.getByText('1 unsaved change')).toBeVisible();

    await page.getByLabel('Service class').selectOption({ label: 'Premium' });

    // A silent discard is the one outcome this must not have.
    await expect(page.getByRole('dialog')).toContainText('Switching to a different service class');
    await page.getByRole('button', { name: 'Cancel' }).click();
    await expect(page.getByLabel('Apapa to Surulere fare')).toHaveValue('4321');

    // Confirming does switch, and the edit is gone.
    await page.getByLabel('Service class').selectOption({ label: 'Premium' });
    await page.getByRole('button', { name: 'Discard and switch' }).click();
    await expect(page.getByText('No unsaved changes')).toBeVisible();

    await selectClass(page, 'Any class');
    await expect(page.getByLabel('Apapa to Surulere fare')).toHaveValue(original);
  });
});
