# Generated by Django 6.0.8 on 2026-08-09 16:52

import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.core.migration_operations import EnableRowLevelSecurity


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_kybdocument'),
        ('clients', '0004_whitelabel_clientinvitation'),
        ('fleet', '0001_initial'),
        ('network', '0003_route_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('days_of_week', models.JSONField(default=list)),
                ('departure_time', models.TimeField()),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='businesses.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='network.route')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('service_date', models.DateField()),
                ('scheduled_departure_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('booking_mode', models.CharField(choices=[('reservation', 'Reservation'), ('tap_and_go', 'Tap and go')], max_length=20)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='businesses.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fleet.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='network.route')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduling.schedule')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['service_date', 'scheduled_departure_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('schedule__isnull', False)), fields=('schedule', 'service_date'), name='unique_trip_per_schedule_per_service_date')],
            },
        ),
        EnableRowLevelSecurity('Schedule'),
        EnableRowLevelSecurity('Trip'),
    ]
