# Generated by Django 6.0.8 on 2026-09-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0011_drop_tap_and_go_choice'),
        ('clients', '0005_alter_kycdocument_options_alter_kycdocument_managers_and_more'),
        ('fleet', '0003_vehicletype_trip_class'),
        ('network', '0005_route_available_trip_classes'),
        ('scheduling', '0006_schedule_trip_class_trip_trip_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='actual_arrival_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='actual_departure_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['business', 'service_date'], name='trip_business_service_date'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['business', 'status'], name='trip_business_status'),
        ),
    ]
