# Generated by Django 6.0.8 on 2026-08-06 22:30

import apps.identity.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_platform_staff', models.BooleanField(default=False)),
                ('is_client_staff', models.BooleanField(default=False, help_text='Only meaningful when `client` is set: True routes this user to the client-admin app, False to the customer (passenger) app. Coarse Phase 0 split — full RBAC roles land in Phase 1.')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Django admin site access, distinct from is_client_staff.')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, help_text='NULL for platform staff. Set for tenant-scoped staff and passengers.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='clients.client')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('client__isnull', False)), fields=('client', 'email'), name='unique_email_per_client'), models.UniqueConstraint(condition=models.Q(('client__isnull', True)), fields=('email',), name='unique_email_for_platform_staff')],
            },
            managers=[
                ('objects', apps.identity.models.UserManager()),
            ],
        ),
    ]
