# Generated by Django 6.0.8 on 2026-08-16 17:54

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_seed_phase5_slice2_payments_wallet_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffinvitation',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelManagers(
            name='role',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='staffinvitation',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
