# Generated by Django 6.0.8 on 2026-08-17 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0014_alter_staffinvitation_options_alter_role_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email']},
        ),
    ]
