# Generated by Django 6.0.8 on 2026-08-23 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_alter_business_options_alter_kybdocument_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='currency',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Currency must be a 3-letter ISO 4217 code (e.g. NGN), not a currency name.', regex='^[A-Z]{3}$')]),
        ),
    ]
