# Generated by Django 6.0.8 on 2026-08-26 17:28

import apps.businesses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_alter_business_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira (NGN)'), ('ZAR', 'South African Rand (ZAR)'), ('GHS', 'Ghanaian Cedi (GHS)'), ('KES', 'Kenyan Shilling (KES)'), ('XOF', 'West African CFA Franc (XOF)'), ('USD', 'US Dollar (USD)'), ('BWP', 'Botswana Pula (BWP)')], max_length=8),
        ),
        migrations.AlterField(
            model_name='business',
            name='timezone',
            field=models.CharField(max_length=64, validators=[apps.businesses.models.validate_iana_timezone]),
        ),
    ]
