# Generated by Django 6.0.8 on 2026-08-26 20:30

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models

from apps.core.migration_operations import EnableRowLevelSecurity


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_alter_business_currency_alter_business_timezone'),
        ('clients', '0005_alter_kycdocument_options_alter_kycdocument_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('id_type', models.CharField(choices=[('nin', 'National Identification Number (NIN)'), ('passport', 'International passport'), ('drivers_licence', "Driver's licence"), ('voters_card', "Voter's card")], max_length=30)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='businesses.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client')),
            ],
            options={
                'ordering': ['full_name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        EnableRowLevelSecurity('Director'),
        migrations.AddField(
            model_name='kybdocument',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='businesses.director'),
        ),
    ]
